apiVersion: v1
kind: ReplicationController
metadata:
  name: firstrc
  labels:
    appname: voatingapp
spec:
  replicas: 3
  template: 
     metadata:
        name: firstpod
        labels:
          env: DEV
          tupe: app
     spec:
        containers:
           - name: con1
             image: coolgourav147/nginx-custom
