apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-deployment
  labels:
    app: headless
spec:
  replicas: 3
  selector:
    matchLabels:
      app: headless
  template:
    metadata:
      labels:
        app: headless
    spec:
      containers:
      - name: headless-container
        image: nginx
        ports:
        - containerPort: 8880

---
apiVersion: v1
kind: Service
metadata:
  name: mongodbhlsvc
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    targetPort: 8880
    protocol: TCP
  selector:
    app: headless
