apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
        - name: con1
          image: coolgourav147/nginx-custom
          imagePullPolicy: Never
  tolerations: 
      -  effect: "NoSchedule"
         key: "size"
         operator: "Equal"
         value: "large"

