apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
        - name: con1
          image: coolgourav147/nginx-custom
          imagePullPolicy: Never
  tolerations: 
      -  effect: ""
         key: ""
         operator: "Exists"
         

