apiVersion: v1
kind: Pod
metadata:
  name: pod21
spec:
  containers:
        - name: con1
          image: coolgourav147/nginx-custom
          imagePullPolicy: Never
  nodeSelector:
          size: big
