---

apiVersion: v1

kind: Pod

metadata:

  name: nginx-node-affinity1

  labels:

     app: nginx

spec:

  affinity:

    nodeAffinity:

      requiredDuringSchedulingIgnoredDuringExecution:

        nodeSelectorTerms:

          - matchExpressions:

              - key: gpu
                operator: Exists



  containers:

    - name: nginx

      image: nginx

---

apiVersion: v1

kind: Pod

metadata:

  name: nginx-node-affinity2

spec:

  affinity:

    podAffinity:

      requiredDuringSchedulingIgnoredDuringExecution:

        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nginx
          topologyKey: gpu

  containers:

    - name: nginx

      image: nginx
