apiVersion: v1
kind: Pod
metadata:
  name: pod31
spec:
  containers:
        - name: con1
          image: coolgourav147/nginx-custom
          imagePullPolicy: Never
  affinity:
         nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: size
                      operator: In
                      values:
                         - small
                weight: 1
   
