apiVersion: v1
kind: Pod
metadata:
  name: rlpod
  labels:
    env: DEV
spec:
  containers:
        - name: con1
          image: coolgourav147/nginx-custom 
          resources:
             requests:
               memory: 1Mi
             limits:
               memory: 200Mi
