apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    env: DEV
spec:
  containers:
        - name: con1
          image: coolgourav147/nginx-custom 
          resources:
             requests:
               memory: 200Mi
               cpu : 100m
